//Generated file

const UNKNOWN: &str = "Unknown";

pub const fn map_wmi_to_manufacturer(wmi: &str) -> &'static str {
    match wmi.as_bytes()[0] {
        b'2' => match wmi.as_bytes()[1] {
            b'T' => match wmi.as_bytes()[2] {
                b'U' => "Tri-Star Industries Limited",
                b'1' => "Toyota Motor Manufacturing Canada",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'C' => "Volvo Group Canada, Inc",
                b'5' => "Fca Canada Inc.",
                b'3' => "Fca Canada Inc.",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'V' => "Nova Bus Inc.",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'G' => "Motor Coach Industries Limited",
                b'E' => "Ford Motor Company Of Canada, Ltd.",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'Y' => "New Flyer Industries Canada Ulc",
                b'B' => "Ford Motor Company Of Canada, Ltd.",
                b'A' => "Ford Motor Company Of Canada, Ltd.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'1' => "Daimlerchrysler Commercial Buses North America (Canada)",
                b'5' => "Fca Canada Inc.",
                b'3' => "Fca Canada Inc.",
                b'X' => "Bombardier Recreational Products Inc ",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'5' => "Fca Canada Inc.",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'5' => "Fca Canada Inc.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'J' => "General Motors Llc",
                b'A' => "General Motors Llc",
                b'H' => "General Motors Llc",
                b'0' => "General Motors Llc",
                b'1' => "General Motors Llc",
                b'7' => "General Motors Llc",
                b'4' => "General Motors Llc",
                b'6' => "General Motors Llc",
                b'2' => "General Motors Llc",
                b'3' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'5' => "Fca Canada Inc.",
                b'3' => "Fca Canada Inc.",
                b'M' => "American Motors (Canada) Inc",
                b'1' => "General Motors Llc",
                b'2' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'G' => "Honda Of Canada Mfg., Inc.",
                b'H' => "Honda Of Canada Mfg., Inc.",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'N' => "Ford Motor Company Of Canada, Ltd.",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'3' => "Fca Canada Inc.",
                b'Z' => "Electra Meccanica Vehicles Corporation",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'3' => "Fca Canada Inc.",
                _ => UNKNOWN,
            },
            b'X' => match wmi.as_bytes()[2] {
                b'M' => "Chrysler Group Llc(Usa),Chrysler Canada, Chrysler De Mexico",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'2' => "Suzuki Motor Of America, Inc",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'W' => match wmi.as_bytes()[1] {
            b'E' => match wmi.as_bytes()[2] {
                b'B' => "Evobus Gmbh",
                b'W' => "E-Bility Gmbh",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'D' => "Daimler Chrysler Ag",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'Z' => "Mercedes-Benz Usa, Llc (Sprinter)",
                b'W' => "Mercedes-Benz, Ag",
                b'D' => "Mercedes-Benz Cars",
                b'B' => "Mercedes-Benz Cars",
                _ => UNKNOWN,
            },
            b'1' => match wmi.as_bytes()[2] {
                b'Z' => "Mercedes-Benz, Ag",
                b'K' => "Mercedes-Benz Cars",
                _ => UNKNOWN,
            },
            b'2' => match wmi.as_bytes()[2] {
                b'Z' => "Mercedes-Benz, Ag",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'K' => "Evobus Gmbh",
                _ => UNKNOWN,
            },
            b'0' => match wmi.as_bytes()[2] {
                b'6' => "Adam Opel Ag",
                b'4' => "Adam Opel Ag",
                b'V' => "General Motors Llc",
                b'8' => "Adam Opel Ag",
                b'L' => "Adam Opel Ag",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'U' => "Audi Ag",
                b'P' => "Bmw Of North America, Llc",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'A' => "Audi Sport Gmbh",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'A' => "Bmw Ag",
                b'Y' => "Bmw Ag",
                b'S' => "Bmw M Gmbh",
                b'C' => "Boom Trikes Fahrzeugbau Ag",
                b'1' => "Bmw Ag Motorcycles",
                b'3' => "Bmw Ag Motorcycles",
                b'4' => "Bmw Ag Motorcycles",
                b'7' => "Black Tea Motorbikes Gmbh",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'W' => "Bmw Ag",
                b'E' => "Mercedes-Benz Cars",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'1' => "Bmw Ag",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'0' => "Dr. Ing. H.C.F. Porsche Ag",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'0' => "Ford Werke Ag",
                b'1' => "Ford Werke Ag",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'W' => "Volkswagen Ag",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'K' => "Tinbot Technology Gmbh",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'G' => "Ggc-Global Generation Cult, Gmbh",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'J' => match wmi.as_bytes()[1] {
            b'H' => match wmi.as_bytes()[2] {
                b'C' => "Hino Motors, Ltd.",
                b'2' => "Honda Motor Co., Ltd",
                b'3' => "Honda Motor Co., Ltd",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'7' => "Isuzu Motors Limited, Japan",
                b'1' => "Isuzu Motors Limited, Japan",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'H' => "Toyota Motor Corporation",
                b'D' => "Toyota Motor Corporation",
                b'N' => "Toyota Motor Corporation",
                b'2' => "Toyota Motor Corporation",
                b'8' => "Toyota Motor Corporation",
                b'5' => "Toyota Motor Corporation",
                b'K' => "Toyota Motor North America, Inc",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'1' => "Subaru Corporation",
                b'4' => "Fuji Heavy Industries U.S.A., Inc. (C/O Subaru Of America)",
                b'E' => "Zhejiang Senling Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'7' => "Suzuki Motor Of America, Inc",
                b'1' => "General Motors Llc",
                b'2' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'1' => "Nissan Motor Company, Ltd",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors Corporation (Mmc)",
                b'4' => "Mitsubishi Motors Corporation (Mmc)",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors Corporation (Mmc)",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'4' => "Mitsubishi Motors Corporation (Mmc)",
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'1' => "Mazda Motor Corporation",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'1' => "Mazda Motor Corporation",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors Corporation (Mmc)",
                b'B' => "Isuzu Motors Limited, Japan",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'1' => "Daihatsu Motor Co., Ltd.",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'S' => "Suzuki Motor Of America, Inc",
                b'8' => "Kawasaki Motors, Ltd",
                b'A' => "Kawasaki Motors, Ltd",
                b'B' => "Kawasaki Motors, Ltd",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'K' => "Suzuki Motor Of America, Inc",
                b'L' => "Suzuki Motor Of America, Inc",
                b'1' => "Suzuki Motor Of America, Inc",
                b'A' => "Suzuki Motor Of America, Inc",
                _ => UNKNOWN,
            },
            b'Y' => match wmi.as_bytes()[2] {
                b'4' => "Yamaha Motor Corporation",
                b'A' => "Yamaha Motor Co., Ltd.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'S' => match wmi.as_bytes()[1] {
            b'F' => match wmi.as_bytes()[2] {
                b'E' => "Alexander Dennis Limited",
                b'Z' => "Tesla, Inc.",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'B' => "Bentley Motors Limited",
                b'F' => "Aston Martin Lagonda Limited",
                b'C' => "Lotus Cars Ltd.",
                b'A' => "Rolls Royce Motor Cars",
                b'R' => "Carbodies Ltd",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'X' => "Austin Rover Group Limited",
                b'J' => "Jaguar Land Rover Limited",
                b'T' => "Triumph Motor Company",
                b'Y' => "Norton Motorcycles Uk Ltd",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'Z' => "Autocar Limited",
                b'K' => "Nissan Motor Manufacturing (Uk) Ltd",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'H' => "Honda Of The U.K. Mfg., Ltd.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'M' => "Mclaren Automotive Limited",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'T' => "Triumph Motor Company",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'C' => "Vectrix Sp. Z O.O.",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'Z' => "Muz Of North America",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'E' => "Govecs Ag",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'1' => match wmi.as_bytes()[1] {
            b'B' => match wmi.as_bytes()[2] {
                b'A' => "Blue Bird Body Company",
                b'5' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'H' => "Daimlerchrysler Commercial Buses North America",
                b'W' => "Volkswagen Group Of America, Inc.",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'G' => "Gillig Llc",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'A' => "General Motors Llc",
                b'J' => "General Motors Llc",
                b'F' => "The Flxible Corporation",
                b'2' => "General Motors Llc",
                b'3' => "General Motors Llc",
                b'8' => "General Motors Llc",
                b'1' => "General Motors Llc",
                b'4' => "General Motors Llc",
                b'6' => "General Motors Llc",
                b'0' => "General Motors Llc",
                b'7' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'5' => "Fca Us Llc",
                b'3' => "Fca Us Llc",
                b'U' => "Cushman A Division Of Outboard Marine Corporation",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'5' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'5' => "Fca Us Llc",
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'5' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'B' => "Ford Motor Company",
                b'A' => "Ford Motor Company",
                b'7' => "Ford Motor Company",
                b'L' => "Ford Motor Company",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'U' => "Silver Eagle Bus Manufacturing, Inc",
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'U' => "Transportation Manufacturing Corporation ",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'8' => "Motor Coach Industries, Inc.",
                b'R' => "Ford Motor Company",
                b'E' => "Ford Motor Company",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'L' => "The Londoncoach Company, Incorporated",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'4' => "Nissan North America, Inc.",
                b'X' => "New United Motor Manufacturing, Inc.",
                _ => UNKNOWN,
            },
            b'Y' => match wmi.as_bytes()[2] {
                b'1' => "New United Motor Manufacturing, Inc.",
                b'V' => "Auto Alliance International, Usa",
                b'J' => "Rokon International, Inc.",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'7' => "Golden Age Auto Corp",
                b'J' => "Owosso Motor Car Company",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'N' => "Ford Motor Company",
                b'1' => "Ford Motor Company",
                _ => UNKNOWN,
            },
            b'X' => match wmi.as_bytes()[2] {
                b'A' => "Excalibur Automobile Corporation",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'G' => "American Honda Motor Co., Inc.",
                b'F' => "American Honda Motor Co., Inc.",
                b'D' => "Harley-Davidson Motor Company",
                _ => UNKNOWN,
            },
            b'9' => match wmi.as_bytes()[2] {
                b'X' => "American Honda Motor Co., Inc.",
                b'U' => "American Honda Motor Co., Inc.",
                b'V' => "American Honda Motor Co., Inc.",
                b'Z' => "Ultra Acquisition Corporation ",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'V' => "Auto Alliance International, Usa",
                b'W' => "Auto Alliance International, Usa",
                _ => UNKNOWN,
            },
            b'2' => match wmi.as_bytes()[2] {
                b'A' => "Avanti Motor Corporation",
                _ => UNKNOWN,
            },
            b'4' => match wmi.as_bytes()[2] {
                b'3' => "Zoe Motors, Inc ",
                _ => UNKNOWN,
            },
            b'1' => match wmi.as_bytes()[2] {
                b'Z' => "Badsey Bullet U.S.A., Inc.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'7' => match wmi.as_bytes()[1] {
            b'D' => match wmi.as_bytes()[2] {
                b'L' => "Designline International Holdings, Llc (Usa)",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'Z' => "Proterra Operating Company, Inc.",
                b'R' => "Volvo Car Usa, Llc",
                b'1' => "Ampere Electric Cars, Inc.",
                b'0' => "Ayro Inc",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'F' => "Lion Electric Manufacturing Usa Inc.",
                b'1' => "Boss Motor Inc.",
                b'Y' => "Fly E-Bike Inc.",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'Z' => "Zhejiang Kandi Vehicles Co. Ltd.",
                b'G' => "Vanderhall Motor Works Inc",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'T' => "Sf Motors, Inc.",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'E' => "Ziggy Lsv Inc. (Formerly Ziggy Inc.)",
                b'6' => "P And G Imports, Llc",
                b'F' => "Land Llc",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'7' => "Arcimoto Inc.",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'3' => "Ev Transportation Services, Inc.",
                b'7' => "Tham Corporation",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'E' => "Onyx Motorbikes, Inc.",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'V' => "Rawrr Inc.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'4' => match wmi.as_bytes()[1] {
            b'U' => match wmi.as_bytes()[2] {
                b'7' => "Country Coach Corporation",
                b'S' => "Bmw Manufacturer Corporation / Bmw North America",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'R' => "Ic Bus, Llc",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'L' => "Safari Motor Coaches",
                b'3' => "Subaru Of America, Inc",
                _ => UNKNOWN,
            },
            b'R' => match wmi.as_bytes()[2] {
                b'K' => "Nova Bus (Us) Inc.",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'1' => "Toyota Motor Manufacturing, Kentucky, Inc.",
                b'4' => "Toyota Motor Manufacturing, Northern Kentucky, Inc.",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'R' => "Renaissance Cars Inc",
                b'M' => "Heritage Marketing Inc.",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors North America",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors North America",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'3' => "General Motors Llc",
                b'5' => "General Motors Llc",
                b'1' => "General Motors Llc",
                b'2' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                b'R' => "Classic Roadsters, Ltd.",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                b'7' => "Global Motorsport Group, Inc.",
                _ => UNKNOWN,
            },
            b'3' => match wmi.as_bytes()[2] {
                b'C' => "Consulier Industries, Inc.",
                b'3' => "Kkm Enterprises",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'0' => "Vectrix Corporation",
                b'A' => "Atk America, Inc.",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'W' => "Westinghouse Electric Corporation",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'8' => "American Honda Motor Co., Inc.",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'M' => "Emb Incorporated",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'D' => "Stroker Cycles, Inc",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'L' => match wmi.as_bytes()[1] {
            b'T' => match wmi.as_bytes()[2] {
                b'S' => "International Transit Systems, Ltd.",
                b'U' => "Nine Tech Co., Ltd.",
                b'D' => "Taixing Sandi Motorcycle Co., Ltd.",
                b'4' => "Taizhou Jiaojiang Zhiwei Motorcycle Manufacture Co., Ltd.",
                b'B' => "Guangdong Qingxin Liantong Industry Co. Ltd.",
                b'8' => "China Taishan Group, Taishan, Haofu, Dajinya",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'0' => "Byd Auto Industry Company Limited",
                b'2' => "Kwang Yang Motor Co., Ltd (Kymco)",
                b'6' => "Suzuki Motor Of America, Inc",
                b'4' => "Chongqing Liyang Jiayu Motorcycle Co., Ltd.",
                b'E' => "Zhejiang Cfmoto Power Co., Ltd",
                b'3' => "Wuxi Jinhong Motorcycle Co., Ltd",
                _ => UNKNOWN,
            },
            b'W' => match wmi.as_bytes()[2] {
                b'E' => "Dongfeng Yangtse Motor (Wuhan) Co., Ltd Dba Wuxi An Yuan Automobile Company",
                b'B' => "American Honda Motor Co., Inc.",
                b'G' => "Chongqing Huansong Industries (Group) Co., Ltd.",
                b'0' => "Wenzhou Light Motorcycle Co. Ltd. (Powersports)",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'C' => "Beiqi Foton Motor Co., Ltd. Beijing Bus Branch Com",
                b'E' => "Beiqi Foton Motor Co., Ltd. Beijing Bus Branch Com",
                b'P' => "Dfsk Motor Co.,Ltd.",
                b'Y' => "Daqing Volvo Car Manufacturing Co Ltd",
                b'N' => "Nogas Electric Scooter Co.",
                b'2' => "Jiangsu Lvneng Electrical Bicycle Technology Co., Ltd.",
                b'7' => "Jinan Qingqi Motorcycle Co., Ltd.",
                b'W' => "First United Industrial Foshan Limited",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'8' => "Anhui Ankai Automobile Co., Ltd.",
                b'N' => "Changzhou Yamasaki Motorcycle Co. Ltd.",
                b'Y' => "Nanfang Space Navigation Science & Technology Co., Ltd.",
                b'T' => "Luoyang Northern Ek Chor Motorcycle Co., Ltd.",
                b'E' => "Jinan Dalong Vehicle Industry Co. Ltd. (Qingqi Group Motorcycle Co. Ltd.)",
                b'W' => "Qianjiang Motorcycles Group Corporation",
                b'L' => "Sundiro Honda Motorcycle Co., Ltd.",
                b'A' => "Shanghai Jialing Vehicle Co., Ltd.",
                b'2' => "Cps Limited",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'K' => "Anyuan Bus Manufacturing Co., Ltd ",
                b'S' => "Zhejiang Haoqing Automobile Mfg Co Ltd",
                b'R' => "Yamaha Motor Corporation",
                b'Y' => "China Baotian Motorcycle Industrial Co. Ltd.",
                b'P' => "Nanchang Aircraft Mfg. Co ( Hongdu Machinery Plant)",
                b'6' => "Guangzhou Panyu Haojian Motorcycle Industry Co., Ltd.",
                b'5' => "Guangzhou Tianma Group Tianma Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'G' => "General Motors Llc",
                b'R' => "Chongqing Hi-Bird Motorcycle Industry Co., Ltd.",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'P' => "China First Automobile Group Imp. % Exp. Corp.",
                b'3' => "Lifan Industry (Group) Company Ltd.",
                b'Y' => "Changshu Light Motorcycle Factory",
                b'E' => "Zhejiang Senling Motorcycle Co., Ltd.",
                b'F' => "Zhejiang Taizhou Wangye Power Co., Ltd.",
                b'G' => "Zhejiang Chuangtai Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'X' => "Byd Auto Co., Ltd.",
                b'0' => "Yongkang Eagle Motor Co.,Ltd",
                _ => UNKNOWN,
            },
            b'R' => match wmi.as_bytes()[2] {
                b'E' => "Shanghai General Motors Corp Ltd.",
                b'Y' => "Chongqing Guangyu Motorcycle Manufacture Co., Ltd.",
                b'P' => "Chongqing Rato Power Co., Ltd.",
                b'4' => "Yadea  Technology Group Co., Ltd.",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'1' => "Suzuki Motor Of America, Inc",
                b'4' => "Zhejiang Kinye Motor Vehicle Co.,Ltd",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'1' => "Suzuki Motor Of America, Inc",
                b'4' => "Suzuki Motor Of America, Inc",
                b'F' => "Jiangmen Zhongyu Motor (Group) Co., Ltd.",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'X' => "Yadea  Technology Group Co., Ltd.",
                b'Z' => "Wuzheng North America Ltd",
                b'M' => "Ningbo Kangda Bicycle Co., Ltd.",
                b'R' => "Jiangsu Dafier Motorcycle Co., Ltd.",
                b'N' => "Jinyun County Xiangyuan Industry Co., Ltd",
                b'Y' => "Taizhou Zhongneng Motorcycle Co., Ltd.",
                b'C' => "Zhejiang Kangdi Vehicles Co. Ltd.",
                b'T' => "Yongkang Mtl Metal Products Co., Ltd.",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'Y' => "Zhejiang Jonway Motorcycle Manufacturing Co., Ltd.",
                b'2' => "Jiangmen Sino-Hongkong Baotian Motorcycle Industrial Co., Ltd.",
                b'X' => "Zhejiang Summit Huawin Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'1' => match wmi.as_bytes()[2] {
                b'T' => "Zhejiang Doohan Technology Co., Ltd.",
                b'3' => "Shandong Baoya New Energy Vehicle Co., Ltd.",
                b'E' => "Taizhou Oming Motorcycle Co., Ltd.",
                b'P' => "Chongquing Dajiang Motorcycles Co., Ltd",
                _ => UNKNOWN,
            },
            b'4' => match wmi.as_bytes()[2] {
                b'B' => "China Xingyue Group Co., Ltd.",
                b'T' => "Tank Sports Inc. A Parent Company Of Pmi Northern Company Ltd.",
                b'Y' => "Ningbo Dalong Smooth Locomotive Industry Co., Ltd.",
                b'H' => "Ningbo Longjia Motorcycle Co., Ltd.",
                b'G' => "Qunsheng Group Co., Ltd.",
                b'S' => "Zhejiang Xingyue Vehicle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'5' => "Benzhou Vehicle Industry Group Co., Ltd",
                b'Y' => "Taizhou Jiaojiang Zhiwei Motorcycle Manufacture Co., Ltd.",
                b'U' => "Chongqing Huanghe Motorcycle Co.,Ltd",
                b'6' => "Zhejiang Leike Machine Industry Co., Ltd.",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'E' => "Dazon , Inc.",
                b'R' => "Juneng Motorcycle Technology Co., Ltd",
                b'B' => "Sanyou Holding Group Yinyou Motorcycle Co., Ltd",
                b'P' => "China Baotian Motorcycle Industrial Co. Ltd.",
                b'X' => "Chongqing Shuangqing Mechanical & Electrical Co. Ltd.",
                b'S' => "Chongqing Zongshen Automobile Industry Co., Ltd.",
                b'L' => "Zengcheng Haili Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'X' => "Exigis, Inc.",
                b'6' => "Hongdou Group Chituma Motorcycle Company",
                b'8' => "Guangzhou Huaye Electric Vehicle Technology Co., Ltd.",
                b'H' => "Zhejiang Riya Motorcycle Co., Ltd.",
                _ => UNKNOWN,
            },
            b'X' => match wmi.as_bytes()[2] {
                b'S' => "Guangzhou Dayang Motorcycle Co., Ltd.",
                b'D' => "Ningbo Dongfang Lingyun Vehicle Made Co., Ltd.",
                b'E' => "Jiangsu Sinski Vehicle Science & Technology Co., Ltd.",
                b'R' => "Jiangsu Xinri E-Vehicle Co.,Ltd.",
                b'K' => "Shanghai Meitian Motorcycle Company Ltd.",
                b'6' => "Jiangmen City Huari Group Co., Ltd.",
                b'Y' => "Chongqing Shineray Motorcycle Co., Ltd.",
                b'M' => "Xiamen Xiashing Motorcycle Co., Ltd.",
                b'A' => "Jiangmen Qipai Motorcycle Co., Ltd",
                _ => UNKNOWN,
            },
            b'6' => match wmi.as_bytes()[2] {
                b'K' => "Shanghai Howhit Machinery Manufacture Co., Ltd",
                b'M' => "Wuxi Tmec Power Technology Co., Ltd.",
                _ => UNKNOWN,
            },
            b'3' => match wmi.as_bytes()[2] {
                b'7' => "Huzhou Daixi Zhenhua Technology Trade Co. Ltd.",
                b'J' => "Jiangsu Sacin Motorcycle Co., Ltd.",
                b'Y' => "Ningbo Motorcycle Factory",
                _ => UNKNOWN,
            },
            b'2' => match wmi.as_bytes()[2] {
                b'B' => "Jiangsu Baodiao Locomotive Co., Ltd.",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'K' => "Jiangsu Jinjie Motor Manufacture Co., Ltd",
                b'X' => "Chongqing Andes Motorcycle Manufacturing Co.,Ltd.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'U' => "Jiangsu Kingbon Vehicle Co., Ltd.",
                b'X' => "Kinroad Xintian Motorcycle Manufacture Co., Ltd.",
                b'5' => "Foshan Fosti Motorcycle Manufacturing Co., Ltd.",
                b'4' => "Chongqing Yinxiang Motorcycle (Group) Co., Ltd.",
                b'B' => "Zhejiang Qianjiang Motorcycle Co., Ltd.",
                b'2' => "Zhejiang Geely Ming Industrial Co., Ltd",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'8' => "Jiangsu Linhai Power Machinery Group Corp.",
                b'0' => "Sanmen County Yongfu Machine Co., Ltd.",
                b'A' => "Shanghai Honling Motorcycle Manufacture Co., Ltd.",
                b'C' => "Chongqing Kinlon Motorcycle Manufacture Co., Ltd",
                b'M' => "Zhejiang Lingtian Motorcycle Co., Ltd",
                b'P' => "Zhejiang Jiajue Motorcycle Manufacturing Co., Ltd.",
                _ => UNKNOWN,
            },
            b'Y' => match wmi.as_bytes()[2] {
                b'X' => "Jiangsu Sinski Sonik Motor Technology Co., Ltd.",
                b'H' => "Ningbo Sanjiang Dykon Motorcycle Co., Ltd.",
                b'S' => "Nanjing Vmoto Manufacturing Co., Ltd.",
                b'D' => "Taizhou City Senlong Motorcycle Manufacture Co.,Ltd.",
                b'E' => "Chongqing Kaier Motorcycle Manufacturing Co.,",
                b'4' => "Chongqing Yingang Science & Technology (Group) Co., Ltd.",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'C' => "Jincheng Corporation",
                b'4' => "Shanghai Jmstar Motorcycle Co., Ltd",
                b'5' => "Cixi Kingring Motorcycle Co., Ltd",
                b'L' => "Zhejiang Lingyu Vehicle Industry Co., Ltd.",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'Z' => "Shanghai Fu Quan Automobile Manufactory Co., Ltd.",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'A' => "Shenzhen Greenwheel Electric Vehicle Co., Ltd.",
                b'J' => "Chongqing Astronautic Bashan Motorcycle Manufacturing Co., Ltd.",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'A' => "Chongqing Hensim Group Co., Ltd.",
                b'J' => "Zhejiang Shanqi Tianying Vehicle Industry Co., Ltd.",
                _ => UNKNOWN,
            },
            b'9' => match wmi.as_bytes()[2] {
                b'N' => "Zhejiang Taotao Vehicles Co.,Ltd",
                _ => UNKNOWN,
            },
            b'0' => match wmi.as_bytes()[2] {
                b'8' => "Zhejiang Jiajue Apollo Vehicle Manufacture Co., Ltd.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'5' => match wmi.as_bytes()[1] {
            b'4' => match wmi.as_bytes()[2] {
                b'R' => "Rev Recreation Group",
                b'T' => "Ukeycheyma",
                b'S' => "Ukeycheyma",
                b'6' => "Buell Motorcycle Co.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'Z' => "Nissan North America, Inc.",
                b'P' => "Solectria Corporation",
                b'J' => "Ives Motors Corporation (Imc)",
                b'6' => "Cannondale Corporation",
                b'B' => "Milwaukee Motorcycle Company",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'Y' => "New Flyer Industries Canada Ulc",
                b'5' => "Esarati Electric Technologies Corp.",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'M' => "Bmw Ag",
                b'V' => "Titan Imports Inc. Dba Us Titan Inc.",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'A' => "Toyota Motor Manufacturing, Kentucky, Inc.",
                b'M' => "Contemporary Classic Cars, Inc.",
                b'F' => "Cleveland Cyclewerks Llc Dba Cultura Scooter Company",
                b'7' => "Lit Motors Corporation",
                b'D' => "Mahindra Tractor Assembly Inc",
                b'N' => "Shockwave Motors, Inc.",
                _ => UNKNOWN,
            },
            b'Y' => match wmi.as_bytes()[2] {
                b'F' => "Toyota Motor Manufacturing, Mississippi, Inc.",
                b'J' => "Tesla, Inc.",
                b'2' => "New United Motor Manufacturing, Inc.",
                b'4' => "Yamaha Motor Corporation",
                b'U' => "Zerteck, Inc.",
                b'L' => "Apex Motor Usa",
                b'A' => "Indian Motorcycle Company",
                b'W' => "Knievel Motorcycle Manufacturing Inc.",
                b'P' => "Trifun, Inc.",
                b'S' => "St Certification Service (Usa) Co., Ltd.",
                _ => UNKNOWN,
            },
            b'3' => match wmi.as_bytes()[2] {
                b'T' => "Think North America Inc.",
                b'J' => "Avera Motors",
                b'G' => "Coda Automotive, Inc.",
                b'8' => "Zero Motorcycles, Inc.",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'X' => "Shelby American, Inc.",
                b'D' => "Indian Motorcycle Company",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'S' => "Mercedes-Benz Cars",
                b'2' => "Evolve Electric Motorcycles",
                b'G' => "Sabertooth Motor Group, Llc",
                _ => UNKNOWN,
            },
            b'0' => match wmi.as_bytes()[2] {
                b'E' => "Lucid Usa, Inc.",
                b'G' => "Karma Automotive Llc",
                b'Y' => "American Ironhorse Llc",
                b'S' => "Mobility Technologies Llc",
                _ => UNKNOWN,
            },
            b'X' => match wmi.as_bytes()[2] {
                b'X' => "Kia Georgia, Inc",
                b'W' => "Alpha Products International, Inc.",
                b'R' => "Luyuan Inc.",
                b'S' => "Street Steel Motorsports, Llc",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'P' => "Hyundai-Kia America Technical Center Inc (Hatci)",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'D' => "General Motors Llc",
                b'8' => "General Motors Llc",
                b'2' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'6' => match wmi.as_bytes()[2] {
                b'N' => "Fortunesport",
                b'A' => "Biketoo, Inc.",
                b'P' => "Faster Faster Inc.",
                b'K' => "Indian Motorcycle Company",
                b'M' => "Switch Vehicles, Inc.",
                _ => UNKNOWN,
            },
            b'2' => match wmi.as_bytes()[2] {
                b'S' => "Equus Automotive, Inc.",
                b'0' => "Bakkura Mobility Inc.",
                b'G' => "California Scooter Company, Llc",
                b'E' => "Amp Motor Vehicles, Inc.",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'B' => "American Honda Motor Co., Inc.",
                b'C' => "American Honda Motor Co., Inc.",
                b'M' => "Vento North America, Llc",
                b'0' => "The Electric Cycle Company",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'C' => "Bug Motors, Inc.",
                _ => UNKNOWN,
            },
            b'W' => match wmi.as_bytes()[2] {
                b'Y' => "Verucci Motorcycles, Llc",
                b'T' => "Aptera Motors Corp.",
                b'R' => "Intrepid Engineering Group (Ieg)",
                b'N' => "Metrorider Llc",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'Z' => "Xtreme Green Products, Inc.",
                b'K' => "American Performance Technologies, Llc",
                b'R' => "Motoadvent, Inc.",
                _ => UNKNOWN,
            },
            b'R' => match wmi.as_bytes()[2] {
                b'4' => "Xkeleton Motorcycle",
                b'D' => "Hitong Motors Corp.",
                b'Y' => "Roketa",
                _ => UNKNOWN,
            },
            b'1' => match wmi.as_bytes()[2] {
                b'R' => "Brammo, Inc.",
                b'D' => "Eco Motor Company, Inc.",
                b'1' => "Mizer Motor Works, Inc.",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'U' => "Astur N.C. Tooling, Inc",
                b'H' => "Excelsior-Henderson Motorcycles",
                b'8' => "Focus  Inc ",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'5' => "American Ironhorse Motorcycle Company, Inc.",
                b'Y' => "Johnny Pag",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'3' => "Baron Motorcycles, Inc.",
                b'8' => "Rc Motorsports, Llc.",
                b'4' => "Power Sports Factory",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'1' => "Big Dog Motorcycles",
                b'E' => "Fast Trac Manufacturing Inc",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'C' => "Cruisers Manufacturing, Inc.",
                b'Y' => "Thoroughbred Motorsports Inc.",
                b'M' => "Titan Motorcycle Company Of America",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'G' => "Massimo Motor Sports, Llc",
                b'E' => "Pagsta. Llc Limited Liability Company",
                b'S' => "Lightning Motors Corp",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'X' => "Millennium Cycles, Inc. ",
                b'0' => "Nst Inc.",
                b'R' => "Kuryente Enterprises, Llc",
                _ => UNKNOWN,
            },
            b'9' => match wmi.as_bytes()[2] {
                b'U' => "Spira4U Llc",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'A' => "Suzuki Motor Of America, Inc",
                b'J' => "Avanti Motorcycles Inc.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'V' => match wmi.as_bytes()[1] {
            b'N' => match wmi.as_bytes()[2] {
                b'E' => "Irisbus France",
                b'K' => "Toyota Motor Manufacturing, France, S.A.S.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'8' => "Renault Group",
                b'5' => "Yamaha Motor Corporation",
                b'A' => "Peugeot Motorcycles",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'4' => "Bluecar, Sas ",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'1' => "Renault Group",
                b'3' => "Automobiles Peugeot",
                _ => UNKNOWN,
            },
            b'X' => match wmi.as_bytes()[2] {
                b'1' => "Sour Zavodi Crvena Zastava Dba Yugo America, Inc.",
                _ => UNKNOWN,
            },
            b'R' => match wmi.as_bytes()[2] {
                b'C' => "Verucci Motorcycles, Llc",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'K' => "Ktm Ag",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'M' => "Montesa Honda Sa",
                b'D' => "Montesa Honda Sa",
                b'H' => "Nacional Motor S.A.U.",
                b'T' => "Suzuki Motor Of America, Inc",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'3' => match wmi.as_bytes()[1] {
            b'C' => match wmi.as_bytes()[2] {
                b'E' => "Volvo Group Mexico, S.A. De C.V.",
                b'5' => "Chrysler De Mexico Toluca",
                b'3' => "Chrysler De Mexico Toluca",
                b'G' => "Ktmmex Sa. De Cv.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'M' => "Motor Coach Industries, Inc.",
                b'5' => "Chrysler De Mexico Toluca",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'5' => "Chrysler De Mexico Toluca",
                b'B' => "Bombardier Recreational Products Inc ",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'5' => "Chrysler De Mexico Toluca",
                b'3' => "Chrysler De Mexico Toluca",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'5' => "Chrysler De Mexico Toluca",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'B' => "Dina Autobuses",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'B' => "Ford Motor Company, Mexico",
                b'A' => "Ford Motor Company, Mexico",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'W' => "Bmw Ag",
                b'F' => "Bmw Ag",
                b'E' => "Ford Motor Company, Mexico",
                b'A' => "Ford Motor Company, Mexico",
                b'Z' => "Mazda Motor Manufacturing De Mexico S.A. De C.V.",
                b'Y' => "Mazda Motor Manufacturing De Mexico S.A. De C.V.",
                b'D' => "Mazda Motor Manufacturing De Mexico S.A. De C.V.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'2' => "General Motors Llc",
                b'4' => "General Motors Llc",
                b'3' => "General Motors Llc",
                b'1' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'3' => "Chrysler De Mexico Toluca",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'N' => "Ford Motor Company, Mexico",
                _ => UNKNOWN,
            },
            b'V' => match wmi.as_bytes()[2] {
                b'W' => "Volkswagen De Mexico Sa De Cv",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'1' => "Nissan Mexicana, S.A. De C.V.",
                b'E' => "Polaris Industries Inc.",
                b'S' => "Polaris Industries Inc.",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'P' => "Kia  Mexico S.A. De C.V.",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'G' => "Honda De Mexico",
                b'1' => "Honda De Mexico",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'N' => match wmi.as_bytes()[1] {
            b'L' => match wmi.as_bytes()[2] {
                b'N' => "Karsan Otomotiv Sanayii Ve Tic. A.S.",
                b'T' => "Temsa Skoda Sabanci Ulasim Araclari A.S.",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'T' => "Toyota Motor Manufacturing,Turkey ,Inc.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'8' => match wmi.as_bytes()[1] {
            b'B' => match wmi.as_bytes()[2] {
                b'R' => "Mercedes-Benz Usa, Llc (Sprinter)",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'6' => "Zanella Hnos Y Cia Sa",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'9' => match wmi.as_bytes()[1] {
            b'3' => match wmi.as_bytes()[2] {
                b'V' => "International Truck And Engine Corporation",
                b'2' => "Harley-Davidson Do Brasil Ltda",
                _ => UNKNOWN,
            },
            b'4' => match wmi.as_bytes()[2] {
                b'M' => "Busscar Onibus S.A.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'W' => "Volkswagen Group Of America, Inc.",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'N' => "Triumph Motorcycles Limited",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'2' => "Moto Honda Da Amazonia Ltda.",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'Z' => "Buell Motorcycle Company",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'H' => "Rtm Group Inc.",
                b'A' => "Deceleste Sa",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'Y' => match wmi.as_bytes()[1] {
            b'V' => match wmi.as_bytes()[2] {
                b'3' => "Volvo Car Corporation",
                b'1' => "Volvo Car Corporation",
                _ => UNKNOWN,
            },
            b'S' => match wmi.as_bytes()[2] {
                b'3' => "Saab Cars North America, Inc.",
                b'M' => "Polestar Performance Ab",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'1' => "Oy Saab Valmet Ab",
                _ => UNKNOWN,
            },
            b'Y' => match wmi.as_bytes()[2] {
                b'C' => "Th!Nk Nordic As",
                _ => UNKNOWN,
            },
            b'W' => match wmi.as_bytes()[2] {
                b'2' => "Cake 0 Emission Ab",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'1' => "American Honda Motor Co., Inc.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'U' => match wmi.as_bytes()[1] {
            b'5' => match wmi.as_bytes()[2] {
                b'Y' => "Hyundai-Kia America Technical Center Inc (Hatci)",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'M' => "Torrot Electric Europa S.L.",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'5' => "Lacfamet",
                b'V' => "Volta Motor Company S.L.",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'5' => "Citycom Elektromobilfabrik A/S",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'K' => match wmi.as_bytes()[1] {
            b'L' => match wmi.as_bytes()[2] {
                b'2' => "General Motors Llc",
                b'1' => "General Motors Llc",
                b'A' => "Gm Daewoo Auto & Technology Company",
                b'5' => "Suzuki Motor Of America, Inc",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'H' => "Hyundai Motor Co",
                b'T' => "Hyundai Motor Co",
                b'Y' => "Daelim Motor Co., Ltd",
                b'4' => "Kr Motors Co., Ltd",
                b'1' => "Hyosung Motors & Machinery Inc",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'H' => "Hyundai Motor Co",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'A' => "Kia Corporation",
                b'J' => "Kia Motors (Ford Imports)",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'Z' => match wmi.as_bytes()[1] {
            b'A' => match wmi.as_bytes()[2] {
                b'M' => "Maserati S.P.A.",
                b'R' => "Alfa Romeo S.P.A.",
                b'P' => "Piaggio & C.S.P.A.",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'2' => "Maserati S.P.A.",
                b'G' => "Mv Agusta Motor S.P.A.",
                b'H' => "Di Blasi Industriale Srl",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'R' => "Pininfarina",
                b'A' => "Fca Italy S.P.A.",
                b'F' => "Ferrari S.P.A.",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'W' => "Automobili Lamborghini Spa",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'N' => "Benelli Q.J. Srl",
                b'0' => "Motor Bike Imports, Inc",
                b'2' => "Moto Meteora ",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'3' => "Betamotor S.P.A.",
                b'C' => "American Honda Motor Co., Inc.",
                b'4' => "Aprilia S.P.A.",
                b'M' => "Ducati Motor Holding S.P.A. ",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'N' => "Energica Motor Company Spa",
                b'0' => "Swm Motorcycles S.R.L.",
                _ => UNKNOWN,
            },
            b'J' => match wmi.as_bytes()[2] {
                b'T' => "Mod Cycles Corp.",
                b'P' => "Piccoli Motori S.R.L.",
                b'M' => "Malaguti S.P.A.",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'U' => "Moto Guzzi S.P.A",
                b'Z' => "Oxygen S.P.A",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'V' => "Moto Laverda Spa",
                _ => UNKNOWN,
            },
            b'K' => match wmi.as_bytes()[2] {
                b'H' => "Husqvarna Motorcycles S.R.L (Formerly Known As Boxer S.R.L., Varese, Italy)",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'1' => "Tomos D.O.O. Motoindustrija",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'X' => match wmi.as_bytes()[1] {
            b'Z' => match wmi.as_bytes()[2] {
                b'1' => "Nov Luxembourg S.A.",
                _ => UNKNOWN,
            },
            b'T' => match wmi.as_bytes()[2] {
                b'B' => "Classic Motorcycles & Sidecars, Inc.",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'J' => "Irbitski Mototsicletny Zavod",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'6' => match wmi.as_bytes()[1] {
            b'G' => match wmi.as_bytes()[2] {
                b'1' => "General Motors Llc",
                b'2' => "General Motors Llc",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'M' => "Mitsubishi Motors Australia Ltd.",
                b'P' => "Ford Motor Co Of Australia Ltd.",
                b'D' => "Braaap Motorcycle Pty Ltd",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'M' => match wmi.as_bytes()[1] {
            b'L' => match wmi.as_bytes()[2] {
                b'3' => "Mitsubishi Motors Corporation (Mmc)",
                b'H' => "Thai Honda Co., Ltd.",
                b'P' => "Tiger Motor Co., Ltd.",
                b'W' => "Sco Motor Co., Ltd",
                b'5' => "Kawasaki Motors, Ltd",
                b'0' => "Ducati Motor (Thailand) Co., Ltd. ",
                _ => UNKNOWN,
            },
            b'N' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'3' => "Fca Us Llc",
                _ => UNKNOWN,
            },
            b'H' => match wmi.as_bytes()[2] {
                b'3' => "Yamaha Motor Corporation",
                b'4' => "Kawasaki Motors, Ltd",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'2' => "Bajaj Auto Ltd",
                b'E' => "Kinetic Engineering Ltd.",
                _ => UNKNOWN,
            },
            b'E' => match wmi.as_bytes()[2] {
                b'3' => "Royal Enfield, A Unit Of Eicher Motors Ltd.",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'F' => "Royal Enfield, A Unit Of Eicher Motors Ltd.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'T' => match wmi.as_bytes()[1] {
            b'R' => match wmi.as_bytes()[2] {
                b'U' => "Audi Ag",
                _ => UNKNOWN,
            },
            b'M' => match wmi.as_bytes()[2] {
                b'C' => "Thompson Mfg. Company Wexford Ltd.",
                _ => UNKNOWN,
            },
            b'A' => match wmi.as_bytes()[2] {
                b'P' => "Polaris Industries Inc.",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'J' => "American Jawa Ltd ",
                b'F' => "Kuberg S.R.O",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'M' => "Quantya Sa",
                _ => UNKNOWN,
            },
            b'C' => match wmi.as_bytes()[2] {
                b'P' => "Peraves Ag",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'R' => match wmi.as_bytes()[1] {
            b'K' => match wmi.as_bytes()[2] {
                b'R' => "Yamaha Motor Taiwan Co., Ltd.",
                b'1' => "E-Ton Power Tech Co., Ltd.",
                b'6' => "Suzuki Motor Of America, Inc",
                b'7' => "Suzuki Motor Of America, Inc",
                b'Z' => "Taiwan Helio Technology Co., Ltd.",
                b'C' => "Rhino Power Sport Industrial Co., Ltd",
                b'P' => "Aero Motorsports, Llc",
                _ => UNKNOWN,
            },
            b'F' => match wmi.as_bytes()[2] {
                b'4' => "Chyong Horng Enterprise Co., Ltd.",
                b'3' => "Aeon Motor Co., Ltd",
                b'L' => "Her Chee Industrial Co., Ltd.",
                b'8' => "Evt Technology Co., Ltd.",
                b'Z' => "E-Ton America, Llc.",
                b'T' => "Cpi Motor Co.",
                b'B' => "Kwang Yang Motor Co., Ltd (Kymco)",
                b'C' => "Taiwan Golden Bee Company",
                b'R' => "Standard Motor Corporation",
                b'G' => "Sanyang Motor Co., Ltd. (Sym)",
                _ => UNKNOWN,
            },
            b'G' => match wmi.as_bytes()[2] {
                b'S' => "Kwang Yang Motor Co., Ltd (Kymco)",
                b'1' => "Apex Motor Usa",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'8' => "Lifan-Vietnam Motor Co., Ltd.",
                b'H' => "Honda Vietnam Co., Ltd.",
                b'7' => "Gelimex",
                b'P' => "Vietnam Kwang Yang Motor Co., Ltd.",
                _ => UNKNOWN,
            },
            b'2' => match wmi.as_bytes()[2] {
                b'L' => "Hongdu Electric Vehicle Hongkong Co.,Limited",
                b'W' => "Smarda Industry & Trade Co., Limited",
                b'X' => "Hk Puviter International Co., Limited",
                b'F' => "Winmax Asia Limited",
                b'V' => "Dogebos Industrial Co., Limited",
                _ => UNKNOWN,
            },
            b'1' => match wmi.as_bytes()[2] {
                b'N' => "Niu Technologies Group Limited",
                b'2' => "Xinri E-Vehicle Hongkong Co., Limited",
                _ => UNKNOWN,
            },
            b'3' => match wmi.as_bytes()[2] {
                b'B' => "Munro Technology Co.,Limited",
                b'M' => "Mangosteen Technology Co., Limited",
                b'J' => "Denzel Motors Co.,Limited",
                b'6' => "Yongkang Changpao Industry And Trade Co., Ltd.",
                b'W' => "Hong Kong Runhorse Holding Co., Limited",
                b'8' => "King Hk International Trading Limited",
                _ => UNKNOWN,
            },
            b'4' => match wmi.as_bytes()[2] {
                b'N' => "Elyx Smart Technology Holdings (Hongkong) Limited",
                b'1' => "Wuxi Tenghui Electric Vehicle Hk Co.,Limited",
                b'5' => "Xl Holding Group (Hk) Co., Limited",
                b'C' => "Doufeng Vehicle Co., Limited",
                b'X' => "Futengda Vehicle(Hk) Limited",
                b'6' => "Wuxi Xiyao Intelligent Technology Co Ltd",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'6' => "Yongkang Liqian Industry And Trade Co., Limited",
                b'C' => "(Hong Kong) Sumec Co, Ltd",
                b'H' => "Hanbird Technology(Hongkong) Limited",
                _ => UNKNOWN,
            },
            b'P' => match wmi.as_bytes()[2] {
                b'G' => "Gck Industrial Usa",
                _ => UNKNOWN,
            },
            b'7' => match wmi.as_bytes()[2] {
                b'M' => "Cnreally Known Corporation Limited",
                b'5' => "Anchi Motorcycle Technology Limited",
                b'N' => "Dayi Intelligent Technology Co. Limited",
                b'4' => "Mking Technology (Hongkong) Co., Limited",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'N' => "Heli Motorcycle Technology Limited",
                b'F' => "Skyblue Motors (Hk) Co., Limited",
                b'C' => "Wuxi Tenghui International Co., Limited",
                _ => UNKNOWN,
            },
            b'6' => match wmi.as_bytes()[2] {
                b'J' => "Newbot (Hk) Co., Limited",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'A' => match wmi.as_bytes()[1] {
            b'2' => match wmi.as_bytes()[2] {
                b'B' => "Usa Motortoys, Llc",
                _ => UNKNOWN,
            },
            b'4' => match wmi.as_bytes()[2] {
                b'Z' => "Zero Motorcycles, Inc.",
                _ => UNKNOWN,
            },
            b'5' => match wmi.as_bytes()[2] {
                b'L' => "Activmo Auto Inc.",
                b'T' => "Jinhua Regard Manufacturing Company Usa",
                _ => UNKNOWN,
            },
            b'6' => match wmi.as_bytes()[2] {
                b'H' => "Hisun Motors Corp.,Usa",
                _ => UNKNOWN,
            },
            b'8' => match wmi.as_bytes()[2] {
                b'M' => "Massimo Motor Sports, Llc",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        b'H' => match wmi.as_bytes()[1] {
            b'A' => match wmi.as_bytes()[2] {
                b'6' => "Jiangsu Niu Electric Technology Co., Ltd.",
                _ => UNKNOWN,
            },
            b'0' => match wmi.as_bytes()[2] {
                b'D' => "Taizhou Qianxin Vehicle Co,.Ltd.",
                _ => UNKNOWN,
            },
            b'Z' => match wmi.as_bytes()[2] {
                b'2' => "Taizhou Zhilong Technology Co.,Ltd",
                _ => UNKNOWN,
            },
            b'B' => match wmi.as_bytes()[2] {
                b'3' => "Hsu Dragon Technology Co., Ltd.",
                _ => UNKNOWN,
            },
            b'U' => match wmi.as_bytes()[2] {
                b'3' => "Chongqing Qiulong Technology Co., Ltd",
                _ => UNKNOWN,
            },
            b'L' => match wmi.as_bytes()[2] {
                b'3' => "Zhejiang Langxiang Industry Co.,Ltd.",
                b'4' => "Zhejiang Morini Vehicle Co.,Ltd.",
                _ => UNKNOWN,
            },
            b'D' => match wmi.as_bytes()[2] {
                b'1' => "Wuxi Dayang Electric Technology Co., Ltd.",
                _ => UNKNOWN,
            },
            _ => UNKNOWN,
        },
        _ => UNKNOWN,
    }
}
